/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    './.storybook/**/*.{js,ts,jsx,tsx}',
  ],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        ds: {
          surface: 'var(--ds-surface, var(--neutral_00))',
          'surface-subtle': 'var(--ds-surface-subtle, var(--neutral_25))',
          border: 'var(--ds-border, var(--neutral_200))',
          'text-strong': 'var(--ds-text-strong, var(--neutral_900))',
          text: 'var(--ds-text, var(--neutral_700))',
          'text-muted': 'var(--ds-text-muted, var(--neutral_600))',
        },
        brand: {
          25: 'var(--brand_25)',
          50: 'var(--brand_50)',
          100: 'var(--brand_100)',
          200: 'var(--brand_200)',
          300: 'var(--brand_300)',
          400: 'var(--brand_400)',
          500: 'var(--brand_500)',
          600: 'var(--brand_600)',
          700: 'var(--brand_700)',
          800: 'var(--brand_800)',
          900: 'var(--brand_900)',
        },
        error: {
          25: 'var(--error_25)',
          50: 'var(--error_50)',
          100: 'var(--error_100)',
          200: 'var(--error_200)',
          300: 'var(--error_300)',
          400: 'var(--error_400)',
          500: 'var(--error_500)',
          600: 'var(--error_600)',
          700: 'var(--error_700)',
          800: 'var(--error_800)',
          900: 'var(--error_900)',
        },
        neutral: {
          0: 'var(--neutral_00)',
          25: 'var(--neutral_25)',
          50: 'var(--neutral_50)',
          100: 'var(--neutral_100)',
          200: 'var(--neutral_200)',
          300: 'var(--neutral_300)',
          400: 'var(--neutral_400)',
          500: 'var(--neutral_500)',
          600: 'var(--neutral_600)',
          700: 'var(--neutral_700)',
          800: 'var(--neutral_800)',
          900: 'var(--neutral_900)',
          1000: 'var(--neutral_1000)',
        },
      },
      spacing: {
        0: 'var(--spacing_0)',
        0.5: 'var(--spacing_0_5)',
        1: 'var(--spacing_1)',
        1.5: 'var(--spacing_1_5)',
        2: 'var(--spacing_2)',
        2.5: 'var(--spacing_2_5)',
        3: 'var(--spacing_3)',
        4: 'var(--spacing_4)',
        5: 'var(--spacing_5)',
        6: 'var(--spacing_6)',
        8: 'var(--spacing_8)',
        10: 'var(--spacing_10)',
        12: 'var(--spacing_12)',
        16: 'var(--spacing_16)',
        20: 'var(--spacing_20)',
        24: 'var(--spacing_24)',
        32: 'var(--spacing_32)',
      },
      fontFamily: {
        sans: ['var(--font_family_base)'],
      },
      fontSize: {
        'ds-display-xs': ['var(--type-display-xs-size)', { lineHeight: 'var(--type-display-xs-line)' }],
        'ds-text-lg': ['var(--type-text-lg-size)', { lineHeight: 'var(--type-text-lg-line)' }],
        'ds-text-md': ['var(--type-text-md-size)', { lineHeight: 'var(--type-text-md-line)' }],
        'ds-text-sm': ['var(--type-text-sm-size)', { lineHeight: 'var(--type-text-sm-line)' }],
        'ds-text-xs': ['var(--type-text-xs-size)', { lineHeight: 'var(--type-text-xs-line)' }],
      },
      borderRadius: {
        1: 'var(--spacing_1)',
        1.5: 'var(--spacing_1_5)',
        2: 'var(--spacing_2)',
        3: 'var(--spacing_3)',
        6: 'var(--spacing_6)',
        ds: 'var(--radius_8)',
      },
      boxShadow: {
        xs: 'var(--shadow_xs)',
        sm: 'var(--shadow_sm)',
        md: 'var(--shadow_md)',
        lg: 'var(--shadow_lg)',
        xl: 'var(--shadow_xl)',
        'focus-brand': 'var(--shadow_focus-brand)',
        'focus-neutral': 'var(--shadow_focus-neutral)',
        'focus-error': 'var(--shadow_focus-error)',
      },
    },
  },
};
