/** @type {import('tailwindcss').Config} */
const colorScale = (name) => ({
  25: `var(--${name}_25)`,
  50: `var(--${name}_50)`,
  100: `var(--${name}_100)`,
  200: `var(--${name}_200)`,
  300: `var(--${name}_300)`,
  400: `var(--${name}_400)`,
  500: `var(--${name}_500)`,
  600: `var(--${name}_600)`,
  700: `var(--${name}_700)`,
  800: `var(--${name}_800)`,
  900: `var(--${name}_900)`,
});

const typeScale = (name) => [
  `var(--type-${name}-size)`,
  {
    lineHeight: `var(--type-${name}-line)`,
    letterSpacing: `var(--type-${name}-letter)`,
  },
];

module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    './.storybook/**/*.{js,ts,jsx,tsx}',
  ],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        ds: {
          surface: 'var(--ds-surface, var(--neutral_00))',
          'surface-subtle': 'var(--ds-surface-subtle, var(--neutral_25))',
          border: 'var(--ds-border, var(--neutral_200))',
          'text-strong': 'var(--ds-text-strong, var(--neutral_900))',
          text: 'var(--ds-text, var(--neutral_700))',
          'text-muted': 'var(--ds-text-muted, var(--neutral_600))',
        },
        brand: colorScale('brand'),
        error: colorScale('error'),
        warning: colorScale('warning'),
        success: colorScale('success'),
        neutral: {
          0: 'var(--neutral_00)',
          25: 'var(--neutral_25)',
          50: 'var(--neutral_50)',
          100: 'var(--neutral_100)',
          200: 'var(--neutral_200)',
          300: 'var(--neutral_300)',
          400: 'var(--neutral_400)',
          500: 'var(--neutral_500)',
          600: 'var(--neutral_600)',
          700: 'var(--neutral_700)',
          800: 'var(--neutral_800)',
          900: 'var(--neutral_900)',
          1000: 'var(--neutral_1000)',
        },
        special: {
          offwhite: 'var(--off-white)',
          lightening: 'var(--lightening)',
          'midnight-black': 'var(--midnight-black)',
        },
      },
      spacing: {
        0: 'var(--spacing_0)',
        0.5: 'var(--spacing_0_5)',
        1: 'var(--spacing_1)',
        1.5: 'var(--spacing_1_5)',
        2: 'var(--spacing_2)',
        2.5: 'var(--spacing_2_5)',
        3: 'var(--spacing_3)',
        4: 'var(--spacing_4)',
        5: 'var(--spacing_5)',
        6: 'var(--spacing_6)',
        8: 'var(--spacing_8)',
        10: 'var(--spacing_10)',
        12: 'var(--spacing_12)',
        16: 'var(--spacing_16)',
        20: 'var(--spacing_20)',
        24: 'var(--spacing_24)',
        32: 'var(--spacing_32)',
      },
      fontFamily: {
        sans: ['var(--font_family_base)'],
      },
      fontSize: {
        'ds-display-2xl': typeScale('display-2xl'),
        'ds-display-xl': typeScale('display-xl'),
        'ds-display-lg': typeScale('display-lg'),
        'ds-display-md': typeScale('display-md'),
        'ds-display-sm': typeScale('display-sm'),
        'ds-display-xs': typeScale('display-xs'),
        'ds-text-xl': typeScale('text-xl'),
        'ds-text-lg': typeScale('text-lg'),
        'ds-text-md': typeScale('text-md'),
        'ds-text-sm': typeScale('text-sm'),
        'ds-text-xs': typeScale('text-xs'),
      },
      borderRadius: {
        0: 'var(--spacing_0)',
        '2px': 'var(--spacing_0_5)',
        4: 'var(--spacing_1)',
        '6px': 'var(--spacing_1_5)',
        8: 'var(--spacing_2)',
        '10px': 'var(--spacing_2_5)',
        12: 'var(--spacing_3)',
        16: 'var(--spacing_4)',
        20: 'var(--spacing_5)',
        24: 'var(--spacing_6)',
        32: 'var(--spacing_8)',
        40: 'var(--spacing_10)',
        48: 'var(--spacing_12)',
        64: 'var(--spacing_16)',
        80: 'var(--spacing_20)',
        96: 'var(--spacing_24)',
        128: 'var(--spacing_32)',
        1: 'var(--spacing_1)',
        1.5: 'var(--spacing_1_5)',
        2: 'var(--spacing_2)',
        3: 'var(--spacing_3)',
        6: 'var(--spacing_6)',
        ds: 'var(--radius_8)',
      },
      boxShadow: {
        xs: 'var(--shadow_xs)',
        sm: 'var(--shadow_sm)',
        md: 'var(--shadow_md)',
        lg: 'var(--shadow_lg)',
        xl: 'var(--shadow_xl)',
        '2xl': 'var(--shadow_2xl)',
        '3xl': 'var(--shadow_3xl)',
        'focus-brand': 'var(--shadow_focus-brand)',
        'focus-neutral': 'var(--shadow_focus-neutral)',
        'focus-error': 'var(--shadow_focus-error)',
      },
    },
  },
};
